### ISSUE TITLE
Deprecate HTML imports and implement ES6 modules

### ISSUE THREAD

**Issue by jarrodek** [mulesoft/api-console#600]
API console version 4 and 5 uses HTML imports to manage dependencies. HTML imports spec is deprecated and soon will be removed from Chrome (M73).

This ticket is to: 

- remove support for HTML imports
- add support for ES6 modules
- update documentation
- update build tools (CLI + corresponding modules)
- publish console (back) to NPM

Current status:

- [x] All components (dependencies) are upgraded
- [x] API Console is upgraded to use ES6 modules
- [ ] Builder modules are upgraded
- [ ] CLI tool is upgraded
- [ ] Documentation is updated 
- [ ] API Console published to NPM

**Comment by jarrodek** [comment]
Fixed in 6.0.0
